#!/bin/bash

echo Initializing custom setup ...

# Install packages
sudo apt-get update
[ -n "$WAYLAND_DISPLAY" ] && clip_tool=wl-clipboard || clip_tool=xclip
sudo apt-get install -y git vim-gtk3 tmux "$clip_tool" fzf alacritty

# .bashrc additions
config_line=". ~/bin/.bashrc"
config_segment="
# PERSONAL ADDITIONS
$config_line
"
if [[ -z "$(cat ~/.bashrc | grep "$config_line")" ]]
    then
        echo "$config_segment" >> ~/.bashrc
        echo Config added to .bashrc!
    else
        echo Config in .bashrc had already been set up!
fi

# .vimrc additions
config_line="source ~/bin/.vimrc"
config_segment="
\" PERSONAL ADDITIONS
$config_line
"
touch ~/.vimrc
if [[ -z "$(cat ~/.vimrc | grep "$config_line")" ]]
    then
        echo "$config_segment" >> ~/.vimrc
        echo Config added to .vimrc!
    else
        echo Config in .vimrc had already been set up!
fi

# .tmux.conf additions
config_line="source-file ~/bin/.tmux.conf"
config_segment="
# PERSONAL ADDITIONS
$config_line
"
touch ~/.tmux.conf
if [[ -z "$(cat ~/.tmux.conf | grep "$config_line")" ]]
    then
        echo "$config_segment" >> ~/.tmux.conf
        echo Config added to .tmux.conf!
    else
        echo Config in .tmux.conf had already been set up!
fi

# alacritty config
my_config=~/bin/alacritty/alacritty.toml
local_config=~/.config/alacritty/alacritty.toml
additional_config=~/.config/alacritty/alacritty_additional.toml
if diff --new-file "$local_config" "$my_config" > /dev/null; then
    # Local config and config in bin/ are the same
    echo Config for alacritty had already been set up!
else
    mkdir --parents ~/.config/alacritty
    cp --backup=numbered "$my_config" "$local_config"
    touch "$additional_config"
    echo Config for alacritty set up!
fi

# git config
git config --global core.excludesfile ~/bin/.gitignore_global
git config --global core.editor vim
git config --global init.defaultbranch main
git config --global advice.detachedhead false
git config --global diff.tool vimdiff
git config --global difftool.prompt false
git config --global alias.adog "log --all --decorate --oneline --graph"
echo "Config for git (global) set up!"

echo Setup complete!

