#!/bin/bash

echo Initializing custom setup ...

# Install packages
sudo apt-get update
sudo apt-get install -y vim-gtk3 tmux wl-clipboard fzf

# .bashrc additions
config_line=". ~/bin/.bashrc"
config_segment="
# PERSONAL ADDITIONS
$config_line
"
if [[ -z "$(cat ~/.bashrc | grep "$config_line")" ]]
    then
        echo "$config_segment" >> ~/.bashrc
        echo Config added to .bashrc!
    else
        echo Config in .bashrc had already been set up!
fi

# .vimrc additions
config_line="source ~/bin/.vimrc"
config_segment="
\" PERSONAL ADDITIONS
$config_line
"
touch ~/.vimrc
if [[ -z "$(cat ~/.vimrc | grep "$config_line")" ]]
    then
        echo "$config_segment" >> ~/.vimrc
        echo Config added to .vimrc!
    else
        echo Config in .vimrc had already been set up!
fi

# .tmux.conf additions
config_line="source-file ~/bin/.tmux.conf"
config_segment="
# PERSONAL ADDITIONS
$config_line
"
touch ~/.tmux.conf
if [[ -z "$(cat ~/.tmux.conf | grep "$config_line")" ]]
    then
        echo "$config_segment" >> ~/.tmux.conf
        echo Config added to .tmux.conf!
    else
        echo Config in .tmux.conf had already been set up!
fi

echo Setup complete!

