#!/bin/bash

usage() {
echo "Usage: recite [TITLE]"
exit 1
}

if [[ ! $1 ]]; then usage; fi

file_directory="${HOME}/Documents/text/pesmi/"
file_name="${1}.txt"
file_path="${file_directory}${file_name}"

if [[ ! -f $file_path ]]; then
	echo "Invalid title argument: $1"
	exit 1
fi

clear
while read -N1 character; do
	printf %s "$character"
	sleep 0.1
done < "$file_path"

