#!/bin/bash

setup_sessions() {
if $(tmux ls > /dev/null 2>&1); then
    echo ERROR: tmux server already running!
    return 1
fi

here=$(pwd)

s0=todo
cd
tmux new-session -d -s "$s0" -n todo 'todo --open'
tmux new-window -t "$s0":2
tmux select-window -t "$s0":1
echo 0: "$s0"

s1=bin
cd ~/bin
todo --list | grep -xq '\* bin' || todo --new bin
tmux new-session -d -s "$s1"
tmux new-window -t "$s1":2
tmux new-window -t "$s1":3 -n todo 'todo --open bin'
tmux select-window -t "$s1":1
echo 1: "$s1"

if [ -f ~/bin/.sessions ]; then
    . ~/bin/.sessions
fi

cd "$here"
tmux attach-session -t "$s0" \; detach
}


setup_sessions

