#!/bin/bash

setup_sessions() {
if $(tmux ls > /dev/null 2>&1); then
    echo ERROR: tmux server already running!
    return 1
fi

here=$(pwd)

s0=todo
cd
tmux new-session -d -s "$s0"
tmux send-keys -t "$s0" 'todo' C-m
tmux new-window -t "$s0"
tmux select-window -t "$s0":1
echo 0: "$s0"

s1=bin
cd ~/bin
todo -l | grep -xq '\* bin' || todo -n bin
tmux new-session -d -s "$s1"
tmux new-window -t "$s1"
tmux new-window -t "$s1" -n 'todo'
tmux send-keys -t "$s1" 'todo -o bin' C-m
tmux select-window -t "$s1":1
echo 1: "$s1"

if [ -f ~/bin/.sessions ]; then
    . ~/bin/.sessions
fi

cd "$here"
tmux attach-session -t "$s0" \; detach
}


setup_sessions

