#!/bin/bash

speakers_id='C0:28:8D:3F:25:2C'
is_not_connected_flag="Connected: no"
info_string=$(echo "info $speakers_id" | bluetoothctl)

echo "Toggling connection to speakers ..."

if echo "$info_string" | grep -q "$is_not_connected_flag"; then
    echo power on | bluetoothctl > /dev/null
    sleep 0.5
    echo "connect $speakers_id" | bluetoothctl > /dev/null
    echo Connected.
else
    echo "disconnect $speakers_id" | bluetoothctl > /dev/null
    echo power off | bluetoothctl > /dev/null
    echo Disconnected.
fi

