#!/bin/bash

speakers_id=C0:28:8D:3F:25:2C
is_connected_flag="Connected: yes"
info_string=$(echo -e "info $speakers_id" | bluetoothctl)

echo "Toggling connection to speakers ..."

if [[ $info_string != *"$is_connected_flag"* ]]; then
	echo -e "power on" | bluetoothctl
	sleep 0.5
	echo -e "connect $speakers_id" | bluetoothctl
else
	echo -e "disconnect $speakers_id" | bluetoothctl
	echo -e "power off" | bluetoothctl
fi

