#!/bin/bash

function usage() {
cat << EOF
Usage: todo [OPTION]
Display the contents of the todo.md file.

Options:
  -h, --help    display this help and exit  
  -v, --vim     open the todo.md file in vim

Exit status:
  0    if everything OK,
  1    otherwise.
EOF
}

todo_file=~/Documents/text/todo.md
input_without_spaces="${1// }"
case $input_without_spaces in
    "" )
        cat $todo_file
        ;;

    -h | --help )
        usage
        ;;

    -v | --vim )
        vim $todo_file
        ;;

    * )
        usage
        (exit 1)
esac

